#!/usr/bin/env bash
# Regenerate packages/server/src/db-types.ts from the database schema.
#
# Requires the Supabase CLI (and, for --local, a running local stack via
# `supabase start`, which needs Docker). Where those are unavailable, the
# checked-in db-types.ts is maintained by hand in the same shape.
#
# Usage:
#   supabase start           # (once) boot the local stack
#   pnpm db:gen-types        # writes packages/server/src/db-types.ts
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/packages/server/src/db-types.ts"

if ! command -v supabase >/dev/null 2>&1; then
  echo "supabase CLI not found. Install it, then re-run (see docs/local-development.md)." >&2
  exit 1
fi

echo "// Generated by \`pnpm db:gen-types\` (supabase gen types). Do not edit by hand." > "$OUT"
supabase gen types typescript --local --schema public >> "$OUT"
echo "Wrote $OUT"
